In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
def get_sites(string, site_type='ACT_SITE'):
    """string=site entry
    Returns the sites as a list, e.g. if 
    string = 'ACT_SITE 85;  /evidence=...; ACT_SITE 110;  /evidence=...'
    returns [85, 110]"""
    
    pattern = re.compile(f'{site_type} [0-9]+;')
    matches = pattern.findall(string)
    get_site = lambda match: int(match.split(' ')[1][:-1])
    return [get_site(match) for match in matches]
get_binding_sites = lambda string: get_sites(string, 'BINDING')

In [3]:
df = pd.read_csv('uniprot.tab', sep='\t', lineterminator='\n')
df = df.fillna('')

In [4]:
df[:5]

Entry   Entry name    Status  \
0  Q9SJT1   SAE2_ARATH  reviewed   
1  P56221   SCYD_MAGO7  reviewed   
2  Q0VCA5  SAMH1_BOVIN  reviewed   
3  O45539   SRC2_CAEEL  reviewed   
4  Q27324   RYK1_DROME  reviewed   

                                       Protein names  \
0  SUMO-activating enzyme subunit 2 (EC 2.3.2.-) ...   
1     Scytalone dehydratase (SD) (SDH) (EC 4.2.1.94)   
2  Deoxynucleoside triphosphate triphosphohydrola...   
3  Tyrosine protein-kinase src-2 (EC 2.7.10.2) (S...   
4  Tyrosine-protein kinase Drl (EC 2.7.10.1) (Pro...   

                        Gene names  \
0  SAE2 EMB2764 At2g21470 F3K23.23   
1                   SDH1 MGG_05059   
2                           SAMHD1   
3             src-2 kin-22 F49B2.5   
4                  drl lio CG17348   

                                            Organism  Length  \
0             Arabidopsis thaliana (Mouse-ear cress)     700   
1  Magnaporthe oryzae (strain 70-15 / ATCC MYA-46...     172   
2                                Bos taurus (Bovine)     589   
3                             Caenorhabditis elegans     507   
4                Drosophila melanogaster (Fruit fly)     610   

                                            Sequence  \
0  MATQQQQSAIKGAKVLMVGAGGIGCELLKTLALSGFEDIHIIDMDT...   
1  MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTL...   
2  MQSADSQNTPKRPRRDGSPRTPPDSPLADAETSPSHDLDPDYRTWG...   
3  MGSCIGKEDPPPGATSPVHTSSTLGRESLPSHPRIPSIGPIAASSS...   
4  MAPNLLTIGLLLTLIASGQAHLNIFLNLHEVLRLIGVSAELYYVRE...   

                                         Active site  \
0  ACT_SITE 168;  /note="Glycyl thioester interme...   
1  ACT_SITE 85;  /evidence="ECO:0000305|PubMed:78...   
2  ACT_SITE 221;  /evidence="ECO:0000250|UniProtK...   
3  ACT_SITE 358;  /note="Proton acceptor";  /evid...   
4  ACT_SITE 468;  /note="Proton acceptor";  /evid...   

                                        Binding site  
0  BINDING 43;  /note="ATP";  /evidence="ECO:0000...  
1  BINDING 30;  /note="Substrate";  /evidence="EC...  
2  BINDING 104;  /note="GTP";  /evidence="ECO:000...  
3  BINDING 268;  /note="ATP";  /evidence="ECO:000...  
4  BINDING 371;  /note="ATP";  /evidence="ECO:000...

In [5]:
df.loc[:, 'Active site'] = df.loc[:, 'Active site'].apply(get_sites)
df.loc[:, 'Binding site'] = df.loc[:, 'Binding site'].apply(get_binding_sites)

In [6]:
df[:5]

Entry   Entry name    Status  \
0  Q9SJT1   SAE2_ARATH  reviewed   
1  P56221   SCYD_MAGO7  reviewed   
2  Q0VCA5  SAMH1_BOVIN  reviewed   
3  O45539   SRC2_CAEEL  reviewed   
4  Q27324   RYK1_DROME  reviewed   

                                       Protein names  \
0  SUMO-activating enzyme subunit 2 (EC 2.3.2.-) ...   
1     Scytalone dehydratase (SD) (SDH) (EC 4.2.1.94)   
2  Deoxynucleoside triphosphate triphosphohydrola...   
3  Tyrosine protein-kinase src-2 (EC 2.7.10.2) (S...   
4  Tyrosine-protein kinase Drl (EC 2.7.10.1) (Pro...   

                        Gene names  \
0  SAE2 EMB2764 At2g21470 F3K23.23   
1                   SDH1 MGG_05059   
2                           SAMHD1   
3             src-2 kin-22 F49B2.5   
4                  drl lio CG17348   

                                            Organism  Length  \
0             Arabidopsis thaliana (Mouse-ear cress)     700   
1  Magnaporthe oryzae (strain 70-15 / ATCC MYA-46...     172   
2                                Bos taurus (Bovine)     589   
3                             Caenorhabditis elegans     507   
4                Drosophila melanogaster (Fruit fly)     610   

                                            Sequence Active site  \
0  MATQQQQSAIKGAKVLMVGAGGIGCELLKTLALSGFEDIHIIDMDT...       [168]   
1  MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTL...   [85, 110]   
2  MQSADSQNTPKRPRRDGSPRTPPDSPLADAETSPSHDLDPDYRTWG...       [221]   
3  MGSCIGKEDPPPGATSPVHTSSTLGRESLPSHPRIPSIGPIAASSS...       [358]   
4  MAPNLLTIGLLLTLIASGQAHLNIFLNLHEVLRLIGVSAELYYVRE...       [468]   

                                        Binding site  
0                                           [43, 67]  
1                                  [30, 50, 53, 131]  
2  [104, 107, 137, 152, 198, 304, 308, 322, 347, ...  
3                                              [268]  
4                                              [371]

# Load into unirep mlstm

In [7]:
import tensorflow as tf

E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
E:\Academic\Scho

In [8]:
# choose 1900_weights or 256_weights, 
# if 1900 weights is chosen during training
# it'll probably be pretty laggy
weight_type = '256_weights'

In [9]:
import os
os.chdir('UniRep')
if weight_type == '1900_weights':
    from unirep import babbler1900 as babbler
elif weight_type == '256_weights':
    from unirep import babbler256 as babbler
os.chdir('../')

W0421 18:12:49.547599  3428 deprecation_wrapper.py:119] From E:\Academic\School\SPRING2020\CS294-150\project\UniRep\unirep.py:43: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.



In [157]:
tf.reset_default_graph()

In [159]:
batch_size = 12
if weight_type == '256_weights':
    b = babbler(batch_size=batch_size, model_path=f'./170_iters_trained_{weight_type}/', trained=True)
elif weight_type == '1900_weights':
    b = babbler(batch_size=batch_size, model_path=f'UniRep/1900_weights/', trained=False)

In [48]:
# get sequences of length less than 275
df_le = df[df['Length']<275]
# get site sequences, 0=normal, 1=active, 2=binding
sequences = []
for i,row in df_le.iterrows():
    seq_len = row['Length']
    site_seq = np.zeros(seq_len+1,dtype=np.int32)
    site_seq[np.array(row['Active site'], dtype=np.int32)] = 1
    site_seq[np.array(row['Binding site'], dtype=np.int32)] = 2
    sequences.append(site_seq)
df_le['Site sequence'] = sequences

c:\users\fores\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


In [49]:
df_le.iloc[0]

Entry                                                       P56221
Entry name                                              SCYD_MAGO7
Status                                                    reviewed
Protein names       Scytalone dehydratase (SD) (SDH) (EC 4.2.1.94)
Gene names                                          SDH1 MGG_05059
Organism         Magnaporthe oryzae (strain 70-15 / ATCC MYA-46...
Length                                                         172
Sequence         MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTL...
Active site                                              [85, 110]
Binding site                                     [30, 50, 53, 131]
Site sequence    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 1, dtype: object

In [50]:
for entry in df_le[:5].iterrows():
    print(entry[1]['Sequence'])

MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTLRIDYRSFLDKLWEAMPAEEFVGMVSSKQVLGDPTLRTQHFIGGTRWEKVSEDEVIGYHQLRVPHQRYKDTTMKEVTMKGHAHSANLHWYKKIDGVWKFAGLKPDIRWGEFDFDRIFEDGRETFGDK
MAIKLIAIDMDGTLLLPDHTISPAVKNAIAAARARGVNVVLTTGRPYAGVHNYLKELHMEQPGDYCITYNGALVQKAADGSTVAQTALSYDDYRFLEKLSREVGSHFHALDRTTLYTANRDISYYTVHESFVATIPLVFCEAEKMDPNTQFLKVMMIDEPAILDQAIARIPQEVKEKYTVLKSAPYFLEILDKRVNKGTGVKSLADVLGIKPEEIMAIGDQENDIAMIEYAGVGVAMDNAIPSVKEVANFVTKSNLEDGVAFAIEKYVLN
MEGQRWLPLEANPEVTNQFLKQLGLHPNWQFVDVYGMEPELLSMVPRPVCAVLLLFPITEKYEVFRTEEEEKIKSQGQDVTSSVYFMKQTISNACGTIGLIHAIANNKDKMHFESGSTLKKFLEESVSMSPEERAKFLENYDAIRVTHETSAHEGQTEAPSIDEKVDLHFIALVHVDGHLYELDGRKPFPINHGKTSDETLLEDAIEVCKKFMERDPDELRFNAIALSAA
MLRLLVVASLVLYGHSTQDFPETNARVVGGTEAQRNSWPSQISLQYRSGSSWAHTCGGTLIRQNWVMTAAHCVDRELTFRVVVGEHNLNQNDGTEQYVGVQKIVVHPYWNTDDVAAGYDIALLRLAQSVTLNSYVQLGVLPRAGTILANNSPCYITGWGLTRTNGQLAQTLQQAYLPTVDYAICSSSSYWGSTVKNSMVCAGGDGVRSGCQGDSGGPLHCLVNGQYAVHGVTSFVSRLGCNVTRKPTVFTRVSAYISWINNVIASN
MAKNRFNQHWLHDHINDPYVKMAQREGYRARAAYKLKEIDEQDKLIRPGQVIVDLGAT

In [51]:
# Before you can train your model, 
with open("formatted.txt", "w") as destination:
    for i,row in df_le.iterrows():
        seq = row['Sequence']
        site_seq = row['Site sequence']
        if b.is_valid_seq(seq): 
            seq = b.format_seq(seq)
            interleaved_seq = np.zeros(2*len(seq), dtype=np.int32)
            # interleave the amino acid sequence and site sequence
            # because this is how we are storing both datas
            interleaved_seq[::2] = seq
            interleaved_seq[1::2] = site_seq+1
            formatted = ",".join(map(str,interleaved_seq))
            destination.write(formatted)
            destination.write('\n')

In [102]:
bucket_op = b.bucket_batch_pad("formatted.txt", lower=200, interval=1000) # Large interval

In [53]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    batch = sess.run(bucket_op)
   
# even indices = amino acid 
# odd indices = site type
print(batch)
print(batch.shape)

[[24  1  1 ...  0  0  0]
 [24  1  1 ...  0  0  0]
 [24  1  1 ...  0  0  0]
 ...
 [24  1  1 ...  0  0  0]
 [24  1  1 ...  0  0  0]
 [24  1  1 ...  0  0  0]]
(12, 522)


In [98]:
final_hidden, x_placeholder, batch_size_placeholder, seq_length_placeholder, initial_state_placeholder = (
    b.get_rep_ops())

In [75]:
def nonpad_len(batch):
    nonzero = batch > 0
    lengths = np.sum(nonzero, axis=1)/2
    return lengths

nonpad_len(batch)

array([211., 261., 222., 155., 243., 231., 259., 194., 248., 156., 232.,
       139.])

In [99]:
optimizer = tf.train.AdamOptimizer(0.001)
all_step_op = optimizer.minimize(b._loss+b.site_loss)

In [100]:
if not os.path.exists(f'./trained_{weight_type}'):
    os.mkdir(f'./trained_{weight_type}')

In [103]:
num_iters = 10
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_iters):
        batch = sess.run(bucket_op)
        seq_batch = batch[:, ::2]
        site_seq_batch = batch[:, 1::2]-1
        length = nonpad_len(batch)-1
        loss, site_loss, _= sess.run([b._loss, b.site_loss, all_step_op],
                                       feed_dict = {
                                        x_placeholder: seq_batch[:, :-1],
                                        b._minibatch_y_placeholder: seq_batch[:, 1:],
                                        b._minibatch_site_y_placeholder: site_seq_batch[:, :-1],
                                        initial_state_placeholder: b._zero_state,
                                        seq_length_placeholder: length,
                                        batch_size_placeholder: batch_size,
                                        b._temp_placeholder: 0.1
                                       })
    
        print(f'Iteration {i}, loss {loss}, site loss {site_loss}')
    b.dump_weights(sess, f'./trained_{weight_type}')

Iteration 0, loss 2.418027877807617, site loss 0.06632212549448013
Iteration 1, loss 2.6590211391448975, site loss 0.05990583077073097
Iteration 2, loss 2.47834849357605, site loss 0.052468378096818924
Iteration 3, loss 2.3766191005706787, site loss 0.032970186322927475
Iteration 4, loss 2.260859727859497, site loss 0.043801527470350266
Iteration 5, loss 2.3772385120391846, site loss 0.035334836691617966
Iteration 6, loss 2.401897668838501, site loss 0.0417235791683197
Iteration 7, loss 2.42256236076355, site loss 0.05541723966598511
Iteration 8, loss 2.4933738708496094, site loss 0.036100130528211594
Iteration 9, loss 2.732053518295288, site loss 0.07392802089452744
Iteration 10, loss 2.6635329723358154, site loss 0.07423851639032364
Iteration 11, loss 2.708963632583618, site loss 0.06306060403585434
Iteration 12, loss 2.4515914916992188, site loss 0.057196225970983505
Iteration 13, loss 2.6229445934295654, site loss 0.06230105087161064
Iteration 14, loss 2.542534112930298, site loss 

rnn/mlstm_stack/mlstm_stack0/mlstm_stack0/wh_0
[[-0.00928485  0.131485   -0.0176266  ... -0.02388142  0.12548566
   0.01738912]
 [ 0.07402053 -0.11893373  0.07463218 ...  0.07346638  0.0097436
   0.07623712]
 [-0.04855222 -0.08517388 -0.16795203 ... -0.0381716  -0.00824911
   0.07425986]
 ...
 [ 0.07275242 -0.0787954  -0.08048905 ...  0.00520771  0.05974585
   0.00707338]
 [-0.07381967 -0.09170253 -0.00133572 ... -0.01604979 -0.05081971
  -0.07252332]
 [ 0.06946802 -0.04032119 -0.0318234  ... -0.03289041  0.00466217
  -0.00185998]]
rnn/mlstm_stack/mlstm_stack0/mlstm_stack0/wmx_0
[[ 0.16382873  0.05630403 -0.14845483 ... -0.00644799  0.09870642
   0.02322426]
 [ 0.04985861  0.02423729 -0.5630881  ...  0.11352421 -0.03789992
  -0.09325295]
 [-0.03713495 -0.89256763  0.13189675 ...  0.20235285 -0.11493229
  -0.16986021]
 ...
 [-0.1065734  -0.21522929  0.09615555 ... -0.02775196  0.06973781
   0.07913216]
 [ 0.14212297 -0.1417697  -0.27732024 ...  0.04597403 -0.04135839
   0.01621333]
 [ 0

rnn/mlstm_stack/mlstm_stack1/mlstm_stack1/b_0
[2.3754277 2.976107  2.5193565 ... 2.987332  2.9413533 2.9654922]
rnn/mlstm_stack/mlstm_stack1/mlstm_stack1/gx_0
[1.5202336  1.016784   1.4368815  ... 0.7947458  0.82361925 0.9679095 ]
rnn/mlstm_stack/mlstm_stack1/mlstm_stack1/gh_0
[0.44924214 1.0357805  0.5657997  ... 1.2975842  1.1003876  1.053306  ]
rnn/mlstm_stack/mlstm_stack1/mlstm_stack1/gmx_0
[1.1751933 1.3212922 1.1636729 1.1631113 1.4819641 1.5298115 1.1514539
 1.1645058 1.40061   1.300175  1.5719898 1.2455817 1.2694904 1.1688881
 1.3387244 1.1536841 1.4201015 1.3587028 1.1556597 1.326893  1.138682
 1.2467049 1.2305502 1.303985  1.2625712 1.2705691 1.3215714 1.4027574
 1.3497617 1.3704476 1.3861476 1.3448986 1.1854132 1.1376216 1.3784536
 1.3170685 1.2504622 1.431862  1.3125067 1.4722791 1.106948  1.1057959
 1.4766636 1.4209594 1.3521017 1.3504008 1.1000206 1.4049609 1.4159548
 1.3370328 1.3112798 1.2971165 1.2673966 1.3447278 1.1750818 1.2968805
 1.3434621 1.2856896 1.3319336 1.23

rnn/mlstm_stack/mlstm_stack3/mlstm_stack3/wh_0
[[-0.02367973 -0.02974045 -0.02649223 ... -0.02444377  0.03891395
  -0.00363523]
 [ 0.0233216   0.04177045  0.05756097 ...  0.01247335 -0.04249682
  -0.00463409]
 [ 0.02864833 -0.01599131  0.11639315 ... -0.00092179 -0.04509701
   0.00058217]
 ...
 [-0.09474472 -0.04012613  0.03596966 ... -0.02181896  0.05833364
   0.00443591]
 [-0.11985058  0.08613998 -0.08589946 ... -0.01807185  0.03476791
   0.01115411]
 [-0.05508594  0.04971914 -0.03197743 ... -0.01787218  0.00176657
   0.00064386]]
rnn/mlstm_stack/mlstm_stack3/mlstm_stack3/wmx_0
[[-0.05808399  0.02797946 -0.05231503 ...  0.03386101 -0.0605932
   0.00601353]
 [ 0.04126847  0.0884276   0.13410449 ... -0.01247062  0.12722942
   0.1186927 ]
 [-0.01316297 -0.05402099  0.03352829 ...  0.13459927 -0.00602077
  -0.12473159]
 ...
 [-0.13466056  0.08199487 -0.00190979 ...  0.06877901 -0.10811007
   0.1470609 ]
 [ 0.00169379  0.03934995  0.16690654 ... -0.04129234  0.12879696
   0.10104791]
 [-0

fully_connected/biases_0
[ 0.02021831 -0.00965756 -0.01219204 -0.01550307 -0.00468482 -0.00283704
 -0.0113952  -0.01003178 -0.02181276 -0.00957449 -0.03120004 -0.14508359
  0.00369329 -0.01132082 -0.00562192 -0.00073138 -0.01050276  0.00447147
 -0.01392512 -0.03374743  0.00720582 -0.16805714 -0.21532083 -0.20415081
 -0.06935377]
fully_connected_1/weights_0
[[-1.12927809e-01 -3.40679772e-02  1.55886456e-01]
 [-1.83609296e-02 -8.25612694e-02 -1.33873284e-01]
 [ 6.74102530e-02 -1.41598970e-01 -4.46544103e-02]
 [ 1.54321656e-01 -9.41583887e-02 -1.87091410e-01]
 [ 1.01843849e-01  1.59715399e-01  1.30861923e-01]
 [-5.67553230e-02 -9.58083421e-02  1.01156846e-01]
 [ 1.76905587e-01 -1.71649307e-02 -1.24152541e-01]
 [ 7.98112527e-02  2.92628594e-02 -1.47613212e-01]
 [-7.49577656e-02  1.69124305e-01  4.34335619e-02]
 [ 2.09095463e-01 -5.79882450e-02 -1.24347173e-01]
 [-8.40610117e-02 -1.14287660e-01 -9.30316821e-02]
 [-3.69472615e-02  1.05160095e-01 -1.45446524e-01]
 [ 7.84057826e-02  1.63912341

## Get the representation of an amino acid sequence

In [114]:
# tensorflow is kinda dumb so you need to do this whenever you initialize a new model 
# of the same type, so if you want to rereun the previous stuff after initializing 
# b_trained you need to go all the way back to the beginning where it also resets the 
# default graph
tf.reset_default_graph()

In [115]:
# set batch size to one to predict next character for one sequence at a time
# in next section
b_trained = babbler(batch_size=1, model_path=f'./170_iters_trained_{weight_type}/', trained=True)

In [149]:
i=np.random.randint(0, 10000)
seq = df_le.iloc[i]['Sequence']
df_le.iloc[i]

Entry                                                       Q634Y5
Entry name                                              AROQ_BACCZ
Status                                                    reviewed
Protein names    3-dehydroquinate dehydratase (3-dehydroquinase...
Gene names                                         aroQ BCE33L3952
Organism                        Bacillus cereus (strain ZK / E33L)
Length                                                         146
Sequence         MKKVLLVNGPNLNRLGVREVNVYGKGTLATLEADMKQEAEAMGVEL...
Active site                                              [23, 100]
Binding site                                     [74, 80, 87, 111]
Site sequence    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 19449, dtype: object

In [89]:
avg_hidden, final_hidden, final_cell = b_trained.get_rep(seq)

## see how well it does on this sequence

In [150]:
batch = np.array([np.array(b_trained.format_seq(seq))])

In [151]:
final_hidden, x_placeholder, batch_size_placeholder, seq_length_placeholder, initial_state_placeholder = (
    b_trained.get_rep_ops())

In [152]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    length = batch[0].shape[0]-1
    loss, logits, sample = sess.run([b_trained._loss, b_trained._logits, b_trained._sample],
                                   feed_dict = {
                                    x_placeholder: batch[:, :-1],
                                    b_trained._minibatch_y_placeholder: batch[:, 1:],
                                    initial_state_placeholder: b_trained._zero_state,
                                    seq_length_placeholder: np.array([length]),
                                    batch_size_placeholder: 1,
                                    b_trained._temp_placeholder: 0.1
                                   })

    print(f'loss {loss}')

loss 2.086141347885132


In [153]:
# 2nd through nth characters of sequence
aas=batch[0][1:]
aas

array([ 1,  4,  4, 16, 21, 21, 16,  9, 13, 14,  9, 21,  9,  2, 21, 13, 16,
        2,  6, 16,  9, 16, 19, 13,  4, 13,  8, 21, 15,  8, 21,  6, 15,  5,
        1,  4, 10,  6, 15,  6, 15,  1, 13, 16,  6, 21,  6, 11, 18, 10,  7,
        9,  3,  6, 13, 15, 17, 17,  5,  2, 17,  3,  6, 15,  6,  5, 17, 19,
        6, 13, 17, 17, 21,  9, 14, 13, 15, 18,  8,  3, 19,  7, 19, 15, 17,
        2,  5, 15, 17, 15,  7, 17,  7, 17, 14, 16, 17,  6, 16,  3, 17,  7,
        9, 17,  3, 10,  2,  6,  7, 18,  2,  3,  6,  7, 16,  8, 15, 15, 16,
       11, 15, 13, 10, 17, 16, 13, 18, 13, 18, 19, 13, 19,  4, 21, 15, 21,
       18, 15, 21,  1,  6,  4, 21,  2,  6, 15])

In [154]:
# predicted 2nd through nth characters of sequence
aas2=sample[0]+1
aas2

array([ 1, 21, 21, 21, 17, 17, 17, 13, 13, 14,  9, 21,  9, 21, 21, 13,  4,
        2,  6, 14,  3,  6,  6, 13,  4,  6,  8, 21,  6,  6, 21,  6,  6, 15,
       21, 15, 15, 15, 13,  6, 15, 15, 13, 17,  5, 16,  6, 16, 18,  8, 15,
        3, 21,  6, 13, 10, 21,  8,  5, 15, 16,  6,  6, 15, 16, 15, 21,  6,
       13, 16, 16, 17, 17, 14, 17, 13, 15, 18,  3,  3, 15, 13, 21, 15,  6,
        6, 15, 13, 21,  4, 15, 16,  4, 17, 14, 16, 17,  6, 17,  3, 17, 14,
        9, 16,  3,  3, 15,  6, 19, 18, 21,  6, 21, 21, 21, 21, 15,  6,  6,
        6, 15, 13, 17, 16, 16, 13, 21, 13, 21, 13, 13,  4, 21, 15, 15, 21,
        6,  6, 15, 15,  6, 15, 13,  4,  6,  4])

In [155]:
print(f"Proportion of amino acids predicted correctly: {np.sum(aas==aas2)/len(aas)}")

Proportion of amino acids predicted correctly: 0.3698630136986301
