In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
def get_sites(string, site_type='ACT_SITE'):
    """string=site entry
    Returns the sites as a list, e.g. if 
    string = 'ACT_SITE 85;  /evidence=...; ACT_SITE 110;  /evidence=...'
    returns [85, 110]"""
    
    pattern = re.compile(f'{site_type} [0-9]+;')
    matches = pattern.findall(string)
    get_site = lambda match: int(match.split(' ')[1][:-1])
    return [get_site(match) for match in matches]
get_binding_sites = lambda string: get_sites(string, 'BINDING')

In [3]:
df = pd.read_csv('uniprot.tab', sep='\t', lineterminator='\n')
df = df.fillna('')

In [4]:
df[:5]

Entry   Entry name    Status  \
0  Q9SJT1   SAE2_ARATH  reviewed   
1  P56221   SCYD_MAGO7  reviewed   
2  Q0VCA5  SAMH1_BOVIN  reviewed   
3  O45539   SRC2_CAEEL  reviewed   
4  Q27324   RYK1_DROME  reviewed   

                                       Protein names  \
0  SUMO-activating enzyme subunit 2 (EC 2.3.2.-) ...   
1     Scytalone dehydratase (SD) (SDH) (EC 4.2.1.94)   
2  Deoxynucleoside triphosphate triphosphohydrola...   
3  Tyrosine protein-kinase src-2 (EC 2.7.10.2) (S...   
4  Tyrosine-protein kinase Drl (EC 2.7.10.1) (Pro...   

                        Gene names  \
0  SAE2 EMB2764 At2g21470 F3K23.23   
1                   SDH1 MGG_05059   
2                           SAMHD1   
3             src-2 kin-22 F49B2.5   
4                  drl lio CG17348   

                                            Organism  Length  \
0             Arabidopsis thaliana (Mouse-ear cress)     700   
1  Magnaporthe oryzae (strain 70-15 / ATCC MYA-46...     172   
2                                Bos taurus (Bovine)     589   
3                             Caenorhabditis elegans     507   
4                Drosophila melanogaster (Fruit fly)     610   

                                            Sequence  \
0  MATQQQQSAIKGAKVLMVGAGGIGCELLKTLALSGFEDIHIIDMDT...   
1  MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTL...   
2  MQSADSQNTPKRPRRDGSPRTPPDSPLADAETSPSHDLDPDYRTWG...   
3  MGSCIGKEDPPPGATSPVHTSSTLGRESLPSHPRIPSIGPIAASSS...   
4  MAPNLLTIGLLLTLIASGQAHLNIFLNLHEVLRLIGVSAELYYVRE...   

                                         Active site  \
0  ACT_SITE 168;  /note="Glycyl thioester interme...   
1  ACT_SITE 85;  /evidence="ECO:0000305|PubMed:78...   
2  ACT_SITE 221;  /evidence="ECO:0000250|UniProtK...   
3  ACT_SITE 358;  /note="Proton acceptor";  /evid...   
4  ACT_SITE 468;  /note="Proton acceptor";  /evid...   

                                        Binding site  
0  BINDING 43;  /note="ATP";  /evidence="ECO:0000...  
1  BINDING 30;  /note="Substrate";  /evidence="EC...  
2  BINDING 104;  /note="GTP";  /evidence="ECO:000...  
3  BINDING 268;  /note="ATP";  /evidence="ECO:000...  
4  BINDING 371;  /note="ATP";  /evidence="ECO:000...

In [5]:
df.loc[:, 'Active site'] = df.loc[:, 'Active site'].apply(get_sites)
df.loc[:, 'Binding site'] = df.loc[:, 'Binding site'].apply(get_binding_sites)

In [6]:
df[:30]

Entry   Entry name    Status  \
0   Q9SJT1   SAE2_ARATH  reviewed   
1   P56221   SCYD_MAGO7  reviewed   
2   Q0VCA5  SAMH1_BOVIN  reviewed   
3   O45539   SRC2_CAEEL  reviewed   
4   Q27324   RYK1_DROME  reviewed   
5   Q8CEG8  UBP27_MOUSE  reviewed   
6   P0A8Y5   YIDA_ECOLI  reviewed   
7   Q9JKB1  UCHL3_MOUSE  reviewed   
8   Q9T0A7   UGE2_ARATH  reviewed   
9   Q9C7W7   UGE4_ARATH  reviewed   
10  Q2L6W9   SAX1_CAEEL  reviewed   
11  Q8VYA3  WAKLJ_ARATH  reviewed   
12  Q9XIE6   ALA3_ARATH  reviewed   
13  P00772    CELA1_PIG  reviewed   
14  P09117    ALDOC_RAT  reviewed   
15  Q8LPK5  CESA8_ARATH  reviewed   
16  Q9FGR9   CEP1_ARATH  reviewed   
17  Q9LF98  ALFC8_ARATH  reviewed   
18  P16152   CBR1_HUMAN  reviewed   
19  P15289   ARSA_HUMAN  reviewed   
20  O35350   CAN1_MOUSE  reviewed   
21  P59807  CABC1_PROVU  reviewed   
22  P51569   AGAL_MOUSE  reviewed   
23  P42575  CASP2_HUMAN  reviewed   
24  P23280   CAH6_HUMAN  reviewed   
25  Q9JHX4    CASP8_RAT  reviewed   
26  A8H8Q9   RLMC_SHEPA  reviewed   
27  Q1CAC8   RLMC_YERPA  reviewed   
28  A7H9A5   RLME_ANADF  reviewed   
29  A0K6C1   RLME_BURCH  reviewed   

                                        Protein names  \
0   SUMO-activating enzyme subunit 2 (EC 2.3.2.-) ...   
1      Scytalone dehydratase (SD) (SDH) (EC 4.2.1.94)   
2   Deoxynucleoside triphosphate triphosphohydrola...   
3   Tyrosine protein-kinase src-2 (EC 2.7.10.2) (S...   
4   Tyrosine-protein kinase Drl (EC 2.7.10.1) (Pro...   
5   Ubiquitin carboxyl-terminal hydrolase 27 (EC 3...   
6                Sugar phosphatase YidA (EC 3.1.3.23)   
7   Ubiquitin carboxyl-terminal hydrolase isozyme ...   
8   UDP-glucose 4-epimerase 2 (AtUGE2) (EC 5.1.3.2...   
9   UDP-glucose 4-epimerase 4 (AtUGE4) (EC 5.1.3.2...   
10  Serine/threonine-protein kinase sax-1 (EC 2.7....   
11  Wall-associated receptor kinase-like 10 (EC 2....   
12  Phospholipid-transporting ATPase 3 (AtALA3) (E...   
13  Chymotrypsin-like elastase family member 1 (EC...   
14  Fructose-bisphosphate aldolase C (EC 4.1.2.13)...   
15  Cellulose synthase A catalytic subunit 8 [UDP-...   
16  KDEL-tailed cysteine endopeptidase CEP1 (EC 3....   
17  Fructose-bisphosphate aldolase 8, cytosolic (A...   
18  Carbonyl reductase [NADPH] 1 (EC 1.1.1.184) (1...   
19  Arylsulfatase A (ASA) (EC 3.1.6.8) (Cerebrosid...   
20  Calpain-1 catalytic subunit (EC 3.4.22.52) (Ca...   
21  Chondroitin sulfate ABC endolyase (EC 4.2.2.20...   
22  Alpha-galactosidase A (EC 3.2.1.22) (Alpha-D-g...   
23  Caspase-2 (CASP-2) (EC 3.4.22.55) (Neural prec...   
24  Carbonic anhydrase 6 (EC 4.2.1.1) (Carbonate d...   
25  Caspase-8 (CASP-8) (EC 3.4.22.61) [Cleaved int...   
26  23S rRNA (uracil(747)-C(5))-methyltransferase ...   
27  23S rRNA (uracil(747)-C(5))-methyltransferase ...   
28  Ribosomal RNA large subunit methyltransferase ...   
29  Ribosomal RNA large subunit methyltransferase ...   

                                    Gene names  \
0              SAE2 EMB2764 At2g21470 F3K23.23   
1                               SDH1 MGG_05059   
2                                       SAMHD1   
3                         src-2 kin-22 F49B2.5   
4                              drl lio CG17348   
5                                 Usp27 Usp27x   
6                            yidA b3697 JW3674   
7                                        Uchl3   
8                     UGE2 At4g23920 T32A16.90   
9   UGE4 REB1 RHD1 At1g64440 F15H21.11 F1N19.2   
10                               sax-1 R11G1.4   
11                  WAKL10 At1g79680 F20B17.10   
12               ALA3 ITB2 At1g59820 F23H11.14   
13                                  CELA1 ELA1   
14                                       Aldoc   
15        CESA8 IRX1 LEW2 At4g18780 F28A21.190   
16                CEP1 CP56 At5g50260 K6A12.12   
17                     FBA8 At3g52930 F8J2_100   
18                        CBR1 CBR CRN SDR21C1   
19                                        ARSA   
20                           Capn1 Canp

# Load into unirep mlstm

In [7]:
import tensorflow as tf

E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
E:\Academic\Scho

In [11]:
import os
os.chdir('UniRep')
from unirep import babbler256 as babbler
os.chdir('../')

In [12]:
batch_size = 12
b = babbler(batch_size=batch_size, model_path='UniRep/256_weights/')

W0419 18:26:50.980488 13364 deprecation_wrapper.py:119] From E:\Academic\School\SPRING2020\CS294-150\project\UniRep\unirep.py:621: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0419 18:26:51.005507 13364 deprecation.py:323] From E:\Academic\School\SPRING2020\CS294-150\project\UniRep\unirep.py:630: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0419 18:26:51.901285 13364 deprecation_wrapper.py:119] From E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\autograph\converters\directives.py:117: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0419 18:26:52.562282 13364 deprecation.py:506] From E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\autograph\impl\api.py:253: calling l

In [13]:
df_le275 = df[df['Length']<275]

In [14]:
df_le275[:50]

Entry   Entry name    Status  \
1    P56221   SCYD_MAGO7  reviewed   
6    P0A8Y5   YIDA_ECOLI  reviewed   
7    Q9JKB1  UCHL3_MOUSE  reviewed   
13   P00772    CELA1_PIG  reviewed   
29   A0K6C1   RLME_BURCH  reviewed   
31   P16608   TRPA_THET2  reviewed   
32   A2BJD9   TDXH_HYPBU  reviewed   
34   A4RGA1  SEC11_MAGO7  reviewed   
36   C5PA33  SEC11_COCP7  reviewed   
43   A7ZYW6   RUTB_ECOHS  reviewed   
44   C8TNC1   RUTB_ECO26  reviewed   
45   B1IV86   RUTB_ECOLC  reviewed   
54   A8QL56   VSP1_OPHHA  reviewed   
56   Q9I8X0   VSP3_DEIAC  reviewed   
57   O13069   VSP2_BOTJA  reviewed   
58   Q71QI3   VSP5_TRIST  reviewed   
61   Q60HC8  UCHL1_MACFA  reviewed   
62   Q91516  VSPPA_TRIST  reviewed   
66   Q4UL59   Y544_RICFE  reviewed   
67   Q9SXC8   UFC1_ARATH  reviewed   
75   Q8TFD5   VER1_DOTSE  reviewed   
77   Q55578   Y361_SYNY3  reviewed   
83   A8XAF4   UFC1_CAEBR  reviewed   
86   Q197B9   VF453_IIV3  reviewed   
88   Q8Z171   ULAB_SALTI  reviewed   
89   P65840   RSUA_SALTY  reviewed   
91   Q2TBG8  UCHL3_BOVIN  reviewed   
97   B4J9W6   UFC1_DROGR  reviewed   
99   Q9HY42  Y3578_PSEAE  reviewed   
114  B4TGJ6   AROD_SALHS  reviewed   
116  Q2NGS8   AROD_METST  reviewed   
120  O86013   BPHF_NOVAR  reviewed   
122  Q5F8N0   AROD_NEIG1  reviewed   
124  A5FRZ6   AROD_DEHMB  reviewed   
125  O46644  CELA1_MACFA  reviewed   
126  A7ZMF8   AROD_ECO24  reviewed   
131  A8A0N9   AROD_ECOHS  reviewed   
133  C0M8T8   AROD_STRE4  reviewed   
134  Q6GB27   AROD_STAAS  reviewed   
135  B2HZQ2   AROE_ACIBC  reviewed   
138  A6T4L2   AROD_KLEP7  reviewed   
139  C1FSW2   AROE_CLOBJ  reviewed   
140  A4FWC6   AROD_METM5  reviewed   
141  O27957   AROE_ARCFU  reviewed   
142  Q24UV9   AROE_DESHY  reviewed   
143  Q8X5X7   AROD_ECO57  reviewed   
145  C5BF12   AROE_EDWI9  reviewed   
148  Q49Y37   AROE_STAS1  reviewed   
151  C3MRB8   AROE_SULIL  reviewed   
159  Q7TS56     CBR4_RAT  reviewed   

                                         Protein names  \
1       Scytalone dehydratase (SD) (SDH) (EC 4.2.1.94)   
6                 Sugar phosphatase YidA (EC 3.1.3.23)   
7    Ubiquitin carboxyl-terminal hydrolase isozyme ...   
13   Chymotrypsin-like elastase family member 1 (EC...   
29   Ribosomal RNA large subunit methyltransferase ...   
31       Tryptophan synthase alpha chain (EC 4.2.1.20)   
32   Peroxiredoxin (EC 1.11.1.15) (Thioredoxin pero...   
34   Signal peptidase complex catalytic subunit SEC...   
36   Signal peptidase complex catalytic subunit SEC...   
43   Peroxyureidoacrylate/ureidoacrylate amidohydro...   
44   Peroxyureidoacrylate/ureidoacrylate amidohydro...   
45   Peroxyureidoacrylate/ureidoacrylate amidohydro...   
54   Alpha- and beta-fibrinogenase OhS1 (EC 3.4.21....   
56   Snake venom serine protease Dav-KN (SVSP) (EC ...   
57   Thrombin-like enzyme KN-BJ 2 (SVTLE) (EC 3.4.2...   
58   Snake venom serine protease CL5 (SVSP) (EC 3.4...   
61   Ubiquitin carboxyl-terminal hydrolase isozyme ...   
62   Venom plasminogen activator TSV-PA (EC 3.4.21....   
66   Uncharacterized RNA pseudouridine synthase RF_...   
67   Ubiquitin-fold modifier-conjugating enzyme 1 (...   
75   Versicolorin reductase 1 (VER-1) (EC 1.1.-.-) ...   
77   Uncharacterized RNA pseudouridine synthase slr...   
83   Ubiquitin-fold modifier-conjugating enzyme 1 (...   
86              Putative thioredoxin-like protein 041R   
88   Ascorbate-specific PTS system EIIB component (...   
89   Ribosomal small subunit pseudouridine synthase...   
91   Ubiquitin carboxyl-terminal hydrolase isozyme ...   
97   Ubiquitin-fold modifier-conjugating enzyme 1 (...   
99       Uncharacterized isomerase PA3578 (EC 5.1.-.-)   
114  3-dehydroquinate dehydratase (3-dehydroquinase...   
116  3-dehydroquinate dehydratase (3-dehydroquinase...   
120  4-hydroxy-2-oxovalerate aldolase (HOA) (EC 4.1...   
122  3-dehydroquinate dehydratase (3-dehydroquinase...   
124  3-dehydroquinate dehydratase (3-dehydroquinase...   
125  Chymotrypsin-like elastase famil

In [15]:
seq = df_le275.iloc[0]['Sequence']
print(seq)

MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTLRIDYRSFLDKLWEAMPAEEFVGMVSSKQVLGDPTLRTQHFIGGTRWEKVSEDEVIGYHQLRVPHQRYKDTTMKEVTMKGHAHSANLHWYKKIDGVWKFAGLKPDIRWGEFDFDRIFEDGRETFGDK


In [16]:
np.array(b.format_seq(seq))

array([24,  1, 13,  7, 10, 16, 10,  4,  7,  5,  6, 17,  8, 18,  7,  5, 19,
       21, 13, 21,  1,  8, 11, 16, 19,  6, 20, 15,  5,  7, 19,  5,  7,  4,
        5, 20,  5,  2, 21,  2,  4, 16, 17, 15, 14,  8, 21,  2, 17,  5, 19,
        2,  7, 18, 21,  5,  4, 21, 20,  6, 15,  1, 14, 15,  6,  6, 18, 16,
       13,  1, 16,  7,  7,  4, 10, 16, 21, 13,  5, 14,  8, 21,  2,  8, 10,
        3, 18, 17, 13, 13,  8,  2, 20,  6,  4, 16,  7,  6,  5,  6, 16, 17,
       13, 19,  3, 10, 21,  2, 16, 14,  3, 10,  2, 19,  4,  5,  8,  8,  1,
        4,  6, 16,  8,  1,  4, 13,  3, 15,  3,  7, 15,  9, 21,  3, 20, 19,
        4,  4, 17,  5, 13, 16, 20,  4, 18, 15, 13, 21,  4, 14,  5, 17,  2,
       20, 13,  6, 18,  5, 18,  5,  2, 17, 18,  6,  5, 13,  2,  6,  8, 18,
       13,  5,  4])

In [17]:
for entry in df_le275[:5].iterrows():
    print(entry[1]['Sequence'])

MGSQVQKSDEITFSDYLGLMTCVYEWADSYDSKDWDRLRKVIAPTLRIDYRSFLDKLWEAMPAEEFVGMVSSKQVLGDPTLRTQHFIGGTRWEKVSEDEVIGYHQLRVPHQRYKDTTMKEVTMKGHAHSANLHWYKKIDGVWKFAGLKPDIRWGEFDFDRIFEDGRETFGDK
MAIKLIAIDMDGTLLLPDHTISPAVKNAIAAARARGVNVVLTTGRPYAGVHNYLKELHMEQPGDYCITYNGALVQKAADGSTVAQTALSYDDYRFLEKLSREVGSHFHALDRTTLYTANRDISYYTVHESFVATIPLVFCEAEKMDPNTQFLKVMMIDEPAILDQAIARIPQEVKEKYTVLKSAPYFLEILDKRVNKGTGVKSLADVLGIKPEEIMAIGDQENDIAMIEYAGVGVAMDNAIPSVKEVANFVTKSNLEDGVAFAIEKYVLN
MEGQRWLPLEANPEVTNQFLKQLGLHPNWQFVDVYGMEPELLSMVPRPVCAVLLLFPITEKYEVFRTEEEEKIKSQGQDVTSSVYFMKQTISNACGTIGLIHAIANNKDKMHFESGSTLKKFLEESVSMSPEERAKFLENYDAIRVTHETSAHEGQTEAPSIDEKVDLHFIALVHVDGHLYELDGRKPFPINHGKTSDETLLEDAIEVCKKFMERDPDELRFNAIALSAA
MLRLLVVASLVLYGHSTQDFPETNARVVGGTEAQRNSWPSQISLQYRSGSSWAHTCGGTLIRQNWVMTAAHCVDRELTFRVVVGEHNLNQNDGTEQYVGVQKIVVHPYWNTDDVAAGYDIALLRLAQSVTLNSYVQLGVLPRAGTILANNSPCYITGWGLTRTNGQLAQTLQQAYLPTVDYAICSSSSYWGSTVKNSMVCAGGDGVRSGCQGDSGGPLHCLVNGQYAVHGVTSFVSRLGCNVTRKPTVFTRVSAYISWINNVIASN
MAKNRFNQHWLHDHINDPYVKMAQREGYRARAAYKLKEIDEQDKLIRPGQVIVDLGAT

In [18]:
with open('seqs.txt', 'w') as f:
    for entry in df_le275[:1000].iterrows():
        f.write(entry[1]['Sequence']+'\n')

In [19]:
# Before you can train your model, 
with open("seqs.txt", "r") as source:
    with open("formatted.txt", "w") as destination:
        for i,seq in enumerate(source):
            seq = seq.strip()
            if b.is_valid_seq(seq) and len(seq) < 275: 
                formatted = ",".join(map(str,b.format_seq(seq)))
                destination.write(formatted)
                destination.write('\n')

In [20]:
bucket_op = b.bucket_batch_pad("formatted.txt", interval=1000) # Large interval

W0419 18:27:13.200328 13364 deprecation_wrapper.py:119] From E:\Academic\School\SPRING2020\CS294-150\project\UniRep\data_utils.py:94: The name tf.string_to_number is deprecated. Please use tf.strings.to_number instead.

W0419 18:27:13.226146 13364 deprecation.py:323] From E:\Academic\School\SPRING2020\CS294-150\project\UniRep\data_utils.py:190: group_by_window (from tensorflow.contrib.data.python.ops.grouping) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.group_by_window(...)`.
W0419 18:27:13.268880 13364 deprecation.py:323] From E:\Academic\School\SPRING2020\CS294-150\project\UniRep\unirep.py:533: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use 

In [21]:
tf.Session()

In [22]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    batch = sess.run(bucket_op)
    
print(batch)
print(batch.shape)

[[24  1 21 ...  0  0  0]
 [24  1  7 ...  0  0  0]
 [24  1 17 ...  0  0  0]
 ...
 [24  1  2 ...  0  0  0]
 [24  1  9 ...  0  0  0]
 [24  1 15 ...  8  6 19]]
(12, 272)


In [23]:
final_hidden, x_placeholder, batch_size_placeholder, seq_length_placeholder, initial_state_placeholder = (
    b.get_rep_ops())

In [25]:
def nonpad_len(batch):
    nonzero = batch > 0
    lengths = np.sum(nonzero, axis=1)
    return lengths

nonpad_len(batch)

array([233, 176, 216, 259, 245, 212, 238, 210,  93, 257, 157, 272])

In [95]:
optimizer = tf.train.AdamOptimizer(0.001)
all_step_op = optimizer.minimize(b._loss)

W0419 20:02:49.353111 13364 deprecation.py:323] From E:\Academic\School\SPRING2020\CS294-150\project\294env\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [96]:
num_iters = 10
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_iters):
        batch = sess.run(bucket_op)
        length = nonpad_len(batch)
        loss, _= sess.run([b._loss, all_step_op],
                                       feed_dict = {
                                        x_placeholder: batch,
                                        b._minibatch_y_placeholder: batch,
                                        initial_state_placeholder: b._zero_state,
                                        seq_length_placeholder: length,
                                        batch_size_placeholder: batch_size,
                                        b._temp_placeholder: 0.1
                                       })
    
        print(f'Iteration {i}, loss {loss}')

Iteration 0, loss 2.9061086177825928
Iteration 1, loss 2.6425487995147705
Iteration 2, loss 1.944445252418518
Iteration 3, loss 1.0570861101150513
Iteration 4, loss 0.6140816807746887
Iteration 5, loss 0.426657110452652
Iteration 6, loss 0.2611452341079712
Iteration 7, loss 0.2098909169435501
Iteration 8, loss 0.14146210253238678
Iteration 9, loss 0.11817871779203415


In [74]:
num_iters = 10
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_iters):
    batch = sess.run(bucket_op)
    length = nonpad_len(batch)
    mask = tf.sign(b._minibatch_y_placeholder)  # 1 for nonpad, zero for pad
    inverse_mask = 1 - mask  # 0 for nonpad, 1 for pad

    total_padded = tf.reduce_sum(inverse_mask)

    pat = (b._minibatch_y_placeholder - 1) + inverse_mask
    
    bl1 = tf.contrib.seq2seq.sequence_loss(
            b._logits, pat, tf.cast(mask, tf.float32))
    
    bl2 = tf.contrib.seq2seq.sequence_loss(
            b._logits, b._sample, tf.cast(mask, tf.float32))
    
    sample, logits, loss, hehe, kap, pa, eg, gs= sess.run([b._sample, b._logits, b._loss,
                                    b._minibatch_y_placeholder,
                                    mask, pad_adjusted_targets, bl1, bl2],
                                   feed_dict = {
                                    x_placeholder: batch,
                                    b._minibatch_y_placeholder: batch,
                                    initial_state_placeholder: b._zero_state,
                                    seq_length_placeholder: length,
                                    batch_size_placeholder: batch_size,
                                    b._temp_placeholder: 0.1
                                   })
    
    

In [75]:
eg

2.9372127

In [76]:
gs

2.229678

In [77]:
kap

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]])

In [79]:
sample

array([[ 0,  6,  3, ..., 13, 13, 13],
       [ 0,  6,  1, ..., 24, 24, 24],
       [ 0,  6,  3, ..., 24, 24, 24],
       ...,
       [ 0,  6,  6, ..., 24, 24, 24],
       [ 0,  6,  6, ..., 24, 24, 24],
       [ 0,  3,  6, ...,  3,  4, 14]])

In [81]:
logits.shape

(12, 274, 25)

In [89]:
logits[0][np.arange(274), pa[0]].mean()

-0.21771824

In [88]:
logits[0].mean()

-2.4704425

In [92]:
(sample[0] == pa)[-1].sum()

16

In [93]:
274/20

13.7